#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
total_screens=$(xrandr -q |grep " connected"|wc -l)

if [ $total_screens -gt 1 ]; then
	
 echo "muiltiple screens"
 bspc monitor eDP1 -d 1 2 3 4 5  
 bspc monitor DP1 -d 6 7 8 9 10
#bspc monitor -d I II III IV V VI VII VIII IX X
else
 bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width        1 
bspc config window_gap          5 
bspc config focused_border_color \#E84F4F
bspc config active_border_color  \#FF0000
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle  true
bspc config top_padding 15 
bspc config ignore_ewmh_struts true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#lauch 
$HOME/.config/bspwm/autostart.sh
